name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Install sbt
        run: curl -Ls https://git.io/sbt > ./sbt && chmod 0755 ./sbt
      - name: Prepare cache
        uses: coursier/cache-action@v6
      - name: Test
        run: ./sbt test
